### ISSUE TITLE
cold you update to the new icons? 

### ISSUE THREAD

**Issue by otmezger** [davidfsmith/AWS-OmniGraffle-Stencils#1]
Hi, there are new icons for AWS (not 3d). There are also some omnigraffle stencils that have those icons in png, but I was wondering if you could update this library to have the new icons in vector format. 

thanks

**Comment by davidfsmith** [comment]
Ok so this in progress with the initial conversion of each icon to a PDF completed.  I'll start working through the creation of the stencils over the next few days - it does take some time though.

**Comment by otmezger** [comment]
Thank you very much, that’ll be awesome!

**Comment by davidfsmith** [comment]
Ok, So I've updated and merged the previous legacy icons (18.02.22) now looking at the new icon set.

**Comment by davidfsmith** [comment]
Oh deep joy - new icon set has light and dark backgrounds

**Comment by davidfsmith** [comment]
Light icons have now been converted, accepting pull requests from anyone that fancies doing the dark backgrounds.
