### ISSUE TITLE
Support for new version releases

### ISSUE THREAD

**Issue by erdaldogan** [davidfsmith/AWS-OmniGraffle-Stencils#16]
Apparently, AWS does not publish the icons in EPS format anymore and they have changed the folder structure as well. Instead of EPS, they provide SVG and PNG files. I suggest updating the convert.sh to support this change. 

With this update, `epstopdf` tool would have become unnecessary, therefore, eliminating the need for `mactex` dependency. Instead, CairoSVG, which is a much lighter dependency, might be used for SVG to PDF conversion.

What do you think?

**Comment by davidfsmith** [comment]
Sounds like a good idea to me, anything that stream lines the process / removes manual steps is a good thing.

**Comment by erdaldogan** [comment]
Turns out there was already a tool that supports newer release format, which is inspired by your work as the author says. I think there is no need to move further with this issue.
 
https://github.com/m-radzikowski/omnigraffle-stencil

**Comment by davidfsmith** [comment]
Looks like I should probably either update this repo, or just retire it.
