### ISSUE TITLE
How to import these stencils into Omnigraffle?

### ISSUE THREAD

**Issue by voxpelli** [davidfsmith/AWS-OmniGraffle-Stencils#4]
Would be great with a note in the README on how to import these stencils into Omnigraffle.

I have never done so before, but seems very useful to be able to draw some AWS charts in Omnigraffle by using these stencils.

**Comment by davidfsmith** [comment]
Fair point, [README.md](https://github.com/davidfsmith/AWS-OmniGraffle-Stencils/blob/master/README.md) updated, hope that helps, if not let me know.
