### ISSUE TITLE
Import error: The data couldn't be read because it isn't in the correct format.

### ISSUE THREAD

**Issue by cruftyoldsysadmin** [davidfsmith/AWS-OmniGraffle-Stencils#6]
Most of the stencils created after running convert.sh fail to import, with the error:

`The data couldn't be read because it isn't in the correct format.`

- My environment is as such:
- Omnigraffle: 7.10.2 (v195.13 r328142)
- OS X: Mojave 10.14.5
- Ghostscript: 9.27
- Mactex: 2019.0508
- xpdf: 4.0.01

The stencil groups which do load properly are:

- Customer Engagement
- Databases
- Machine Learning
- Management & Governance
- Robotics

**Comment by davidfsmith** [comment]
Thanks for raising (I think) I'll take a look at the stencils you have listed.

**Comment by davidfsmith** [comment]
Ok, so to test this I remove the icons from Omnigraffle with a quick `rm -rf` to really make sure as well as doing the same for my git based working directory.

Then cloned the repo and used

    open $HOME/Library/Containers/com.omnigroup.OmniGraffle7.MacAppStore/Data/Library/Application\ Support/The\ Omni\ Group/OmniGraffle/Stencils

to open the stencil directory in finder, made a new directory `AWS` and copied all of the stencil files into it.

Finally opened Omnigraffle and got creative copying various services from the stencil groups you listed above into a beautiful diagram.

So then I got creative and started going through all of the stencil groups and found the following to be problem children

* AR & VR

That was the only stencil that didn't load for me

* Omnigraffle 7.10.2 (v195.13 r328142)
* OSX 10.14.6

**Comment by davidfsmith** [comment]
Just pushed [23a122a](https://github.com/davidfsmith/AWS-OmniGraffle-Stencils/commit/23a122ad0572cb8d4be6865eb41322ed902dd31e) which for me resolves the issue with the AR & VR Stencil.

I'd be interested in knowing if others are having the same issue reported or even with different stencils.

**Comment by huslage** [comment]
I am using OmniGraffle v7.12.1 on Catalina and these `19.10.31` branch stencils give the same error:

* _General
* _Group Icons
* Analytics
* Application Integration
* AR & VR
* Blockchain
* Business Applications
* Compute
* Customer Enablement
* Developer Tools
* End User Computing
* Game Tech
* Internet of Things
* Media Services
* Migration & Transfer
* Mobile
* Networking & Content Delivery
* Satellite
* Security, Identity, & Compliance
* Storage

**Comment by davidfsmith** [comment]
Same here, just not had a chance to look at it since creating the original files using the script.

**Comment by davidfsmith** [comment]
Opened as a new issue as it relates to the new AWS icon set.
