### ISSUE TITLE
Issue with conversion script

### ISSUE THREAD

**Issue by davidfsmith** [davidfsmith/AWS-OmniGraffle-Stencils#9]
`convert.sh` is no longer creating usable stencil files resulting in having to revert back to a manual (and tedious) process to update the stencils when new icon sets are released.

**Comment by LeDoTruongAn** [comment]
Remove/Replace/Decode & symbol then it will solve the problem.

**Comment by davidfsmith** [comment]
Thanks for the tip, looks like there are some updated icons for me to test it on ;-)

**Comment by davidfsmith** [comment]
Ok, so replacing `&` in file and directories names prior to running `convert.sh` appears to be the magic needed to fix things, thanks to @LeDoTruongAn for the suggestion.

**Comment by LeDoTruongAn** [comment]
No worries 💯
